# Numpy

import numpy,
import numpy as np, 
from numpy import *

Arrays : Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int.  Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists. 

===================================================================
#It creates an ndarray from any object exposing array interface
ndarray : numpy.array 
numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
===================================================================

object : Any object exposing the array interface method returns an array, or any (nested) sequence like for example List.
 
dtype : Desired data type of array, optional 
 
copy : Optional. By default (true), the object is copied 
 
order : C (row major) or F (column major) or A (any) (default) 
 
subok : By default, returned array forced to be a base class array. If true, sub-classes passed through 
 
ndimin : Specifies minimum dimensions of resultant array 

## Data Types: 
bool_ Boolean ,
int_ Default ,
intc , 
intp ,
int8 ,
int16 ,
int32 , 
int64 , 
uint8 ,
uint16 , 
uint32 ,
uint64 , 
float_ ,
float16 ,
float32 , 
float64 ,
complex_ ,
complex64 ,
Complex number, ,
complex128 ,
Complex number, ,

In [ ]:
object : Any object exposing the array interface method returns an array, or any (nested) sequence like for example List.

dtype : Desired data type of array, optional

copy : Optional. By default (true), the object is copied

order : C (row major) or F (column major) or A (any) (default)

subok : By default, returned array forced to be a base class array. If true, sub-classes passed through

ndimin : Specifies minimum dimensions of resultant array

In [2]:
import numpy as np

l= [1, 4, 5, 8]
a = np.array(l) 
print(type(a)) 
a

<class 'numpy.ndarray'>


array([1, 4, 5, 8])

## Array elements are accessed, sliced, and manipulated just like lists

In [1]:
print (a[0:2])
print(a[3])

NameError: name 'a' is not defined

## Multidimensional Array:

In [10]:
# Two DImensional
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0,0])
print(a[0])
print(a[1,0])
print(a)
print ('****************')
# THree Dimesnional

a = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(a[0,0,0])
print(a[0,1])
print(a[1,0])
print(a[1])
print(a)

1
[1 2 3]
4
[[1 2 3]
 [4 5 6]]
****************
1
[4 5 6]
[7 8 9]
[[ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Shape : It gives a tuple with the size of each array dimension in reverse manner (ROw first, coulmns next: 3rd Dimesion -2nd Dimension: 1st Dimension):

In [12]:
a.shape

(2, 2, 3)

## Array Should always be of same dimesion , if the dimension mismatch it will become list as ab in below:

In [17]:
a = np.array([[1, 2,3], [4, 5, 6]])
ab= np.array([[1, 2], [4, 5, 6]])
print(a)
print(ab)
print(a.shape)
print(ab.shape)

[[1 2 3]
 [4 5 6]]
[list([1, 2]) list([4, 5, 6])]
(2, 3)
(2,)


## dtype : type of values

In [18]:
a.dtype 

dtype('int32')

## len : returns the length of the first axis:

In [3]:
import numpy as np
a = np.array([[1, 2,3], [4, 5, 6]])
abc = np.array([[1, 2,3], [4, 5, 6],[1, 2,3]])
print(len(a))
len(abc)

2


3

## in : to check if the value is present in the array

In [4]:
x= [1,2,3] in a
y= 1 in a
print(x,y)

True True


## range(x): to create value for range

In [29]:
a = np.array(range(10), float) 
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## reshape: Reshape or redimension of the array

In [12]:
import numpy as np
a = np.array(range(12), float) 
print(a)
a = a.reshape((12, 1))
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]]


## arange: Range method in array which directly return array instead of list

In [19]:
#arrange(start,end,step) 
a= np.arange(1, 30, 3, dtype=int) 
print(a)

[ 1  4  7 10 13 16 19 22 25 28]


## copy : To copy a array from one to another 

In [7]:
a = np.array([1, 2, 3], float) 
b = a 
c = a.copy() 
print(a)
print(b)
print(c)
a[0]=6
print(a)
print(b)
print(c)


[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
[6. 2. 3.]
[6. 2. 3.]
[1. 2. 3.]


## tolist: An array can be converted to list

In [14]:
a = np.array([[1, 2, 3, 4], [1, 2, 3, 4]]) 
a=a.tolist()
print(a)
type(a)

[[1, 2, 3, 4], [1, 2, 3, 4]]


list

## fill: TO fill the complete array with given value

In [10]:
a = np.array([1, 2, 3])
print(a)
a.fill(0)
print(a)

[1 2 3]
[0 0 0]


## flatten: TO make multi dimensional array as one dimension

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
a=a.flatten()
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## concatenate : TO concatenate or joing multiple arrays of one dimesion or multi dimension. 

In [15]:
a = np.array([1,2]) 
b = np.array([3,4,5,6]) 
c = np.array([7,8,9]) 
d= np.concatenate((a, b, c))
print(d)
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
c= np.concatenate((a,b)) # Default concatenate on axis 0. 
print('\n',c)
d= np.concatenate((a,b), axis=0)
print("After concat")
print('\n',d)
e= np.concatenate((a,b), axis=1) 
print('\n',e)

[1 2 3 4 5 6 7 8 9]

 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
After concat

 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]

 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


## Array mathematics: One Dimensioal

## arrays should always be of the same size during addition, subtraction, Multiplication or division

In [28]:
a = np.array([1,2]) 
b = np.array([4,5,6])   
print(a+b) 

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [29]:
a = np.array([1,2,3]) 
b = np.array([4,5,6])   
print(a+b) ## 1+4, 2+5, 3+6
print(a-b) ## 1-4, 2-5, 3-6
print(a*b) ## 1*4, 2*5, 3*6
print(a/b) 
print(a%b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]


## Array mathematics MultiDimensional

In [3]:
import numpy as np
# Two Dimesnional : For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication
#TO do MAtrix multiplication we need to use dot method
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])  
c=a*b
print(c)

[[ 5 12]
 [21 32]]


In [5]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[10,11,12],[13,14,15], [16,17,18]])  
c=a*b
print(a.shape)
print(b.shape)
print(c)

(3, 3)
(3, 3)
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [14]:
a = np.array([5,6])
b = np.array([[1,2], [3,4]])
# In case of multi dimesional array if size doesn not match the tuple will be broadcasted automatically . 
# For Example in above case a will become [5,6], [5,6] automatically 
a+b
# FOr Broadcasting the one varibale should always be on size 1. below will throw error
#a = np.array([[5,6], [7,8]])
#b = np.array([[1,2], [3,4], [5,6]])
#a+b

array([[ 6,  8],
       [ 8, 10]])

## Methods : abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, and arctanh.

In [17]:
print(np.pi) 
print(np.e)
a = np.array([1, 2,3,4])
print( np.sqrt(a))
print( np.abs(a))

3.141592653589793
2.718281828459045
[1.         1.41421356 1.73205081 2.        ]
[1 2 3 4]


## Array iteration and operations

In [18]:
a = np.array([1, 2, 3])
for x in a:
     print (x) 

1
2
3


In [20]:
a = np.array([[1, 2, 3],[4,5,6]])
for x in a:
     print (x)
        

[1 2 3]
[4 5 6]


In [34]:
a = np.array([1, 3, 2])
print(np.sum(a))
print(np.prod(a)) 
print(a.mean()) 
print(a.var())
print(a.std()) 
print(a.min()) 
print(a.max()) 
a.sort()
print(a)
print(np.unique(a)) 

6
6
2.0
0.6666666666666666
0.816496580927726
1
3
[1 2 3]
[1 2 3]


In [36]:
a = np.array([[4,5,6], [1, 3, 2]])
print(np.sum(a))
print(np.prod(a)) 
print(a.mean()) 
print(a.var())
print(a.std()) 
print(a.min()) 
print(a.max()) 
a.sort() # Sort inside the elements like 1,3,2 will be sorted to 1,2,3 . 123 and 456 will not be compared to sorted.
print(a)
print(np.unique(a)) 
print(a.diagonal())

21
720
3.5
2.9166666666666665
1.707825127659933
1
6
[[4 5 6]
 [1 2 3]]
[1 2 3 4 5 6]
[4 2]


## Comparison operators and value testing 

In [17]:
a = np.array([5, 2, 3]) 
b = np.array([3, 4, 5]) 
print(a > b)
print(a == b) 
print(a <= b )

[ True False False]
[False False False]
[False  True  True]


In [40]:
#Arrays can be compared to single values using broadcasting: 
a = np.array([1, 5, 10])
a > 3



array([False,  True,  True])

In [42]:
 #any and all : To determine whether or not any or all elements of a Boolean array are true
c = np.array([ True, False, False])
any(c)
all (c)

False

## indices 

In [43]:
a = np.array([2, 5, 7, 9], float)
b = np.array([0, 1, 0, 2], int)
a[b]

array([2., 5., 2., 7.])

In [44]:
a = np.array([[1, 3], [9, 15]], float)
b = np.array([1, 0, 0, 1], int)
c = np.array([0, 1, 0, 1], int)
a[b,c]

array([ 9.,  3.,  1., 15.])

## MAtrix Multiplicatiosn: dot method

In [46]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [58]:
#In multidimesional

a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]]) 
c = np.array([2, 3])
d=a*b
print(d)
print (np.shape(a))
print (np.shape(c))
print(np.dot(a, b))
print(np.dot(a, c))  

# to apply dot funcation from a and b , second paarameter to shape should always be same. 
#Like a shape (x, y) and b shape (p, q) then y and p should be of same size . 
# Example. 3,2 and 2,3 . Here y and p value is 2. 

p = np.array([[1,2], [3,4], [5,6]])
q = np.array([[5,6], [7,8]])
print (np.shape(p))
print (np.shape(q))
print(np.dot(p, q)) # (3,2 ) dot (2, 2) so should be working fine .
#print(np.dot(q, p)) # should not work as (2,2) dot (3,2) will not work

[[ 5 12]
 [21 32]]
(2, 2)
(2,)
[[19 22]
 [43 50]]
[ 8 18]
(3, 2)
(2, 2)
[[19 22]
 [43 50]
 [67 78]]
